# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\ForgotPassword.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 712)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image: url(\"../SmartStudy/images/premain.png\");\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 20, 751, 651))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 200, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(150, 280, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonXacNhan = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonXacNhan.setGeometry(QtCore.QRect(270, 440, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonXacNhan.setFont(font)
        self.pushButtonXacNhan.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 127);\n"
"    border-radius: 15px;\n"
"    padding: 10px 25px;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #F4A261;\n"
"}\n"
"")
        self.pushButtonXacNhan.setObjectName("pushButtonXacNhan")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(70, 350, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUserName.setGeometry(QtCore.QRect(250, 210, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditEmail.setGeometry(QtCore.QRect(250, 290, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPassWord = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassWord.setGeometry(QtCore.QRect(250, 360, 461, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPassWord.setFont(font)
        self.lineEditPassWord.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPassWord.setObjectName("lineEditPassWord")
        self.back = QtWidgets.QLabel(parent=self.frame)
        self.back.setGeometry(QtCore.QRect(250, 540, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(340, 20, 101, 81))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/key.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(130, 100, 491, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #1E88E5;")
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Quên mật khẩu"))
        self.label_2.setText(_translate("MainWindow", "Tên đăng nhập:"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.pushButtonXacNhan.setText(_translate("MainWindow", "Xác nhận"))
        self.label_3.setText(_translate("MainWindow", "Mật khẩu mới:"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Nhập tên đăng nhập"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Nhập tên email"))
        self.lineEditPassWord.setPlaceholderText(_translate("MainWindow", "Mật khẩu mới"))
        self.back.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"#\"><span style=\" font-size:16pt; text-decoration: underline; color:#0000ff;\">Quay lại trang đăng nhập</span></a></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:40pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#1f74ac;\">Quên mật khẩu</span></p></body></html>"))
