# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\Login.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 712)
        MainWindow.setStyleSheet("QMainWindow{\n"
"                            border-image: url(../SmartStudy/images/premain.png);\n"
"                        }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(180, 40, 681, 611))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(210, 130, 281, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #1F74AC;\n"
"background-color: transparent;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUserName.setGeometry(QtCore.QRect(90, 280, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditUserName.setText("")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassword.setGeometry(QtCore.QRect(90, 370, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPassword.setText("")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLogin.setGeometry(QtCore.QRect(220, 510, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 127);\n"
"    border-radius: 15px;\n"
"    padding: 10px 25px;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #F4A261;\n"
"}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.QuenMatKhau = QtWidgets.QLabel(parent=self.frame)
        self.QuenMatKhau.setGeometry(QtCore.QRect(390, 450, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.QuenMatKhau.setFont(font)
        self.QuenMatKhau.setStyleSheet("background-color: transparent;\n"
"")
        self.QuenMatKhau.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.QuenMatKhau.setObjectName("QuenMatKhau")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(290, 10, 111, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/book.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.checkBoxShowPassword = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBoxShowPassword.setGeometry(QtCore.QRect(130, 460, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBoxShowPassword.setFont(font)
        self.checkBoxShowPassword.setStyleSheet("background-color: transparent;\n"
"")
        self.checkBoxShowPassword.setObjectName("checkBoxShowPassword")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 220, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 85, 127);\n"
"background-color: transparent;\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 30, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(254, 255, 193);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/back.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonBack.setCheckable(False)
        self.pushButtonBack.setAutoDefault(False)
        self.pushButtonBack.setDefault(False)
        self.pushButtonBack.setFlat(False)
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Đăng nhập"))
        self.label_4.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:36pt; font-weight:600; color:#1f74ac;\">Đăng nhập</span></p></body></html>"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Nhập tên đăng nhập"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.QuenMatKhau.setText(_translate("MainWindow", "<a href=\"#\">Quên mật khẩu?</a>"))
        self.checkBoxShowPassword.setText(_translate("MainWindow", "Hiển thị mật khẩu"))
        self.label_2.setText(_translate("MainWindow", "Chào mừng bạn đã quay trở lại!"))
        self.pushButtonBack.setText(_translate("MainWindow", "Quay lại"))
