# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 712)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image: url(\"../SmartStudy/images/mwin.png\");\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgba(255, 255, 255, 30); /* Trắng mờ 30% */\n"
"    border: 1px solid rgba(255, 255, 255, 50);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton#pushButtonMotivation {\n"
"    max-width: 300px;      /* Giới hạn chiều ngang */\n"
"    max-height: 60px;      /* Giới hạn chiều cao */\n"
"    border-radius: 15px;   /* Bo góc để nhìn mềm mại */\n"
"    background-color: rgba(255, 255, 255, 60); /* Nền trắng mờ */\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 50, 721, 211))
        self.frame.setStyleSheet("#frame{\n"
"background-color: rgba(255,255,255,120);\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButtonMotivation = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonMotivation.setGeometry(QtCore.QRect(110, 20, 500, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMotivation.sizePolicy().hasHeightForWidth())
        self.pushButtonMotivation.setSizePolicy(sizePolicy)
        self.pushButtonMotivation.setMinimumSize(QtCore.QSize(500, 100))
        self.pushButtonMotivation.setMaximumSize(QtCore.QSize(302, 62))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonMotivation.setFont(font)
        self.pushButtonMotivation.setStyleSheet("\n"
"color: rgb(26, 116, 172);\n"
"font-size: 30px;\n"
"font-weight: bold;\n"
"background-color: transparent;")
        self.pushButtonMotivation.setObjectName("pushButtonMotivation")
        self.lblNotification = QtWidgets.QLabel(parent=self.frame)
        self.lblNotification.setGeometry(QtCore.QRect(110, 130, 499, 61))
        self.lblNotification.setMinimumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblNotification.setFont(font)
        self.lblNotification.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lblNotification.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblNotification.setObjectName("lblNotification")
        self.pushButtonStatistic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStatistic.setGeometry(QtCore.QRect(90, 460, 261, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonStatistic.setFont(font)
        self.pushButtonStatistic.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background:white;\n"
"border-radius:20px;\n"
"border:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#f2f8ff;\n"
"border:2px solid #4aa3ff;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/target.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonStatistic.setIcon(icon)
        self.pushButtonStatistic.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonStatistic.setObjectName("pushButtonStatistic")
        self.pushButtonRank = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRank.setGeometry(QtCore.QRect(390, 460, 271, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonRank.setFont(font)
        self.pushButtonRank.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background:white;\n"
"border-radius:20px;\n"
"border:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#f2f8ff;\n"
"border:2px solid #4aa3ff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_target.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonRank.setIcon(icon1)
        self.pushButtonRank.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRank.setObjectName("pushButtonRank")
        self.pushButtonExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(700, 460, 251, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonExit.setFont(font)
        self.pushButtonExit.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background:white;\n"
"border-radius:20px;\n"
"border:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#f2f8ff;\n"
"border:2px solid #4aa3ff;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonExit.setIcon(icon2)
        self.pushButtonExit.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonTimetable = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTimetable.setGeometry(QtCore.QRect(180, 320, 301, 111))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTimetable.setFont(font)
        self.pushButtonTimetable.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background:white;\n"
"border-radius:20px;\n"
"border:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#f2f8ff;\n"
"border:2px solid #4aa3ff;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_schedule.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTimetable.setIcon(icon3)
        self.pushButtonTimetable.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonTimetable.setObjectName("pushButtonTimetable")
        self.pushButtonClock = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClock.setGeometry(QtCore.QRect(510, 320, 301, 111))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClock.setFont(font)
        self.pushButtonClock.setStyleSheet("QPushButton{\n"
"color: rgb(0, 0, 0);\n"
"background:white;\n"
"border-radius:20px;\n"
"border:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background:#f2f8ff;\n"
"border:2px solid #4aa3ff;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_clock.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClock.setIcon(icon4)
        self.pushButtonClock.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonClock.setObjectName("pushButtonClock")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Màn hình chính "))
        self.pushButtonMotivation.setText(_translate("MainWindow", "Sống vì chính mình"))
        self.lblNotification.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Hiển thị thông báo</span></p></body></html>"))
        self.pushButtonStatistic.setText(_translate("MainWindow", "Thống kê mục tiêu"))
        self.pushButtonRank.setText(_translate("MainWindow", "Bảng xếp hạng"))
        self.pushButtonExit.setText(_translate("MainWindow", "Thoát"))
        self.pushButtonTimetable.setText(_translate("MainWindow", "Kế hoạch học tập"))
        self.pushButtonClock.setText(_translate("MainWindow", "Đồng hồ đếm ngược"))
