# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\Motivation.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 712)
        MainWindow.setStyleSheet("QMainWindow{\n"
"border-image: url(\"../SmartStudy_het_loi_tkb/images/nen.jpg\");\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 290, 571, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonNew.setGeometry(QtCore.QRect(10, 20, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonNew.setFont(font)
        self.pushButtonNew.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonNew.setIcon(icon)
        self.pushButtonNew.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonSave.setGeometry(QtCore.QRect(210, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSave.setIcon(icon1)
        self.pushButtonSave.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButtonDelete.setGeometry(QtCore.QRect(380, 20, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/ic_delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonDelete.setIcon(icon2)
        self.pushButtonDelete.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 30, 631, 81))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: transparent;")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(130, 140, 651, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("#frame{\n"
"background-color: rgba(255,255,255,120);\n"
"border-radius:20px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.lineEditId = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditId.setGeometry(QtCore.QRect(150, 30, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditId.setFont(font)
        self.lineEditId.setObjectName("lineEditId")
        self.lineEditContent = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditContent.setGeometry(QtCore.QRect(150, 80, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEditContent.setFont(font)
        self.lineEditContent.setObjectName("lineEditContent")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: transparent;\n"
"")
        self.label_4.setObjectName("label_4")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(30, 30, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(255, 251, 183);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/back.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon3)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 380, 671, 241))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("#frame{\n"
"background-color: rgba(255,255,255,120);\n"
"border-radius:20px;\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidgetMotivation = QtWidgets.QListWidget(parent=self.groupBox_2)
        self.listWidgetMotivation.setStyleSheet("")
        self.listWidgetMotivation.setObjectName("listWidgetMotivation")
        self.verticalLayout.addWidget(self.listWidgetMotivation)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Câu động lực"))
        self.pushButtonNew.setText(_translate("MainWindow", "Thêm mới"))
        self.pushButtonSave.setText(_translate("MainWindow", "Lưu"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Xóa"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:19pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#5555ff;\">QUẢN LÝ CHUỖI CÁC CÂU ĐỘNG LỰC</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Câu động lực"))
        self.label_2.setText(_translate("MainWindow", "ID:"))
        self.label_4.setText(_translate("MainWindow", "Nội dung:"))
        self.pushButtonBack.setText(_translate("MainWindow", "Quay lại"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Danh sách câu động lực:"))
