# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\Rank.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 700)
        MainWindow.setStyleSheet("# Dán đoạn này đè lên phần setStyleSheet cũ\n"
"        self.MainWindow.setStyleSheet(f\"\"\"\n"
"            /* Cửa sổ chính: Nền trắng mặc định, chữ đen */\n"
"            QMainWindow {{\n"
"                background-color: white;\n"
"                color: black;\n"
"                font-family: \"\"; /* Xóa bỏ custom font, dùng font mặc định của Qt */\n"
"            }}\n"
"\n"
"            /* Bảng xếp hạng / Danh sách (QListWidget, QTableWidget) */\n"
"            QListWidget, QTableWidget {{\n"
"                background-color: white;\n"
"                color: black;\n"
"                border: 1px solid #C0C0C0; /* Viền xám mỏng mặc định */\n"
"                border-radius: 0px; /* Góc vuông, không bo tròn */\n"
"            }}\n"
"\n"
"            /* Từng dòng trong danh sách */\n"
"            QListWidget::item, QTableWidget::item {{\n"
"                color: black;\n"
"                background-color: transparent;\n"
"                padding: 5px; /* Giãn cách một chút cho dễ đọc */\n"
"                border-bottom: 1px solid #F0F0F0; /* Dòng kẻ mờ ngăn cách */\n"
"            }}\n"
"\n"
"            /* Khi di chuột vào dòng */\n"
"            QListWidget::item:hover, QTableWidget::item:hover {{\n"
"                background-color: #F2F2F2; /* Màu xám rất nhạt khi hover */\n"
"            }}\n"
"\n"
"            /* Khi dòng được chọn (Selection) */\n"
"            QListWidget::item:selected, QTableWidget::item:selected {{\n"
"                color: white;\n"
"                background-color: #0078D7; /* Màu xanh dương mặc định của Windows */\n"
"            }}\n"
"\n"
"            /* Mấy cái khác cho nó đồng bộ \'phèn\' luôn */\n"
"            QLabel {{\n"
"                color: black;\n"
"                background: transparent;\n"
"            }}\n"
"            \n"
"            QPushButton {{\n"
"                background-color: #F0F0F0;\n"
"                color: black;\n"
"                border: 1px solid #A0A0A0;\n"
"                border-radius: 2px; /* Bo góc rất nhẹ của nút mặc định */\n"
"                padding: 4px 8px;\n"
"            }}\n"
"            \n"
"            QPushButton:hover {{\n"
"                background-color: #E1E1E1;\n"
"            }}\n"
"            \n"
"            QPushButton:pressed {{\n"
"                background-color: #C1C1C1;\n"
"            }}\n"
"\n"
"            QLineEdit {{\n"
"                color: black;\n"
"                background-color: white;\n"
"                border: 1px solid #A0A0A0;\n"
"                border-radius: 0px;\n"
"                padding: 2px;\n"
"            }}\n"
"        \"\"\")")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(255, 251, 183);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/back.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayout_2.addWidget(self.pushButtonBack)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setStyleSheet("font: 75 33pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.listWidgetRank = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidgetRank.setMaximumSize(QtCore.QSize(700, 500))
        self.listWidgetRank.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listWidgetRank.setStyleSheet("QListWidget {\n"
"background-color: rgba(255, 255, 255, 90);\n"
"border: 1px solid rgba(255, 255, 255, 50);\n"
"border-radius: 10px;\n"
"font-size: 22px;\n"
"}\n"
"QListWidget::item {\n"
"    min-height: 45px; \n"
"    padding-left: 10px; \n"
"    border-bottom: 1px solid rgba(255, 255, 255, 50);\n"
"}")
        self.listWidgetRank.setObjectName("listWidgetRank")
        self.verticalLayout.addWidget(self.listWidgetRank)
        self.pushButtonRankMe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRankMe.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButtonRankMe.setMaximumSize(QtCore.QSize(700, 16777215))
        self.pushButtonRankMe.setStyleSheet("background-color: rgb(234, 144, 11);\n"
"color: rgb(255, 229, 153);\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;")
        self.pushButtonRankMe.setObjectName("pushButtonRankMe")
        self.verticalLayout.addWidget(self.pushButtonRankMe)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Bảng xếp hạng"))
        self.pushButtonBack.setText(_translate("MainWindow", "Quay lại"))
        self.label.setText(_translate("MainWindow", "BẢNG VÀNG TOP 10 HỌC BÁ"))
        self.pushButtonRankMe.setText(_translate("MainWindow", "Xếp hạng"))
