# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\Register.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1006, 712)
        MainWindow.setStyleSheet("QMainWindow{\n"
"                            border-image: url(../SmartStudy/images/premain.png);\n"
"                        }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(200, 10, 631, 671))
        self.frame.setStyleSheet("QFrame{\n"
"background:white;\n"
"border-radius:15px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditUserName.setGeometry(QtCore.QRect(80, 310, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditEmail.setGeometry(QtCore.QRect(80, 370, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassword.setGeometry(QtCore.QRect(80, 430, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonTaoTaiKhoan = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonTaoTaiKhoan.setGeometry(QtCore.QRect(160, 550, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTaoTaiKhoan.setFont(font)
        self.pushButtonTaoTaiKhoan.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 127);\n"
"    border-radius: 15px;\n"
"    padding: 10px 25px;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #F4A261;\n"
"}\n"
"")
        self.pushButtonTaoTaiKhoan.setObjectName("pushButtonTaoTaiKhoan")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(80, 110, 471, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 170, 255);")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(parent=self.frame)
        self.checkBox.setGeometry(QtCore.QRect(100, 500, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.DangNhap = QtWidgets.QLabel(parent=self.frame)
        self.DangNhap.setGeometry(QtCore.QRect(190, 630, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setUnderline(True)
        self.DangNhap.setFont(font)
        self.DangNhap.setStyleSheet("color:#d62828;\n"
"text-decoration: underline;")
        self.DangNhap.setObjectName("DangNhap")
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditFullName.setGeometry(QtCore.QRect(80, 250, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEditFullName.setFont(font)
        self.lineEditFullName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 91, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/hello.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(110, 190, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_3.setObjectName("label_3")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setGeometry(QtCore.QRect(50, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(254, 255, 193);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/back.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setIconSize(QtCore.QSize(20, 20))
        self.pushButtonBack.setCheckable(False)
        self.pushButtonBack.setAutoDefault(False)
        self.pushButtonBack.setDefault(False)
        self.pushButtonBack.setFlat(False)
        self.pushButtonBack.setObjectName("pushButtonBack")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Đăng ký"))
        self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Nhập tên đăng nhập"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "Nhập tên email"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu"))
        self.pushButtonTaoTaiKhoan.setText(_translate("MainWindow", "Tạo tài khoản"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:36pt; font-weight:600; color:#1f74ac;\">Đăng ký tài khoản</span></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Hiển thị mật khẩu"))
        self.DangNhap.setText(_translate("MainWindow", "<a href=\"#\">Đã có tài khoản? Đăng nhập</a>"))
        self.lineEditFullName.setPlaceholderText(_translate("MainWindow", "Nhập họ và tên"))
        self.label_3.setText(_translate("MainWindow", "Tạo tài khoản mới để bắt đầu hành trình học tập"))
        self.pushButtonBack.setText(_translate("MainWindow", "Quay lại"))
