# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\Statistics.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 700)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonBack.setFont(font)
        self.pushButtonBack.setStyleSheet("background-color: rgb(255, 251, 183);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\SmartStudy_het_loi_tkb\\ui\\../images/back.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBack.setIcon(icon)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayout_4.addWidget(self.pushButtonBack)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(400, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 50))
        self.groupBox_4.setStyleSheet("border: none;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonBefore = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonBefore.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButtonBefore.setStyleSheet("background-color: #0078D7;\n"
"color: white;\n"
"font-family: \'Consolas\';\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"padding: 10px;\n"
"\n"
"")
        self.pushButtonBefore.setObjectName("pushButtonBefore")
        self.horizontalLayout.addWidget(self.pushButtonBefore)
        self.pushButtonAfter = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.pushButtonAfter.setMaximumSize(QtCore.QSize(50, 35))
        self.pushButtonAfter.setStyleSheet("background-color: #0078D7;\n"
"color: white;\n"
"font-family: \'Consolas\';\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"padding: 10px;\n"
"\n"
"")
        self.pushButtonAfter.setObjectName("pushButtonAfter")
        self.horizontalLayout.addWidget(self.pushButtonAfter)
        self.labelDate = QtWidgets.QLabel(parent=self.groupBox_4)
        self.labelDate.setMinimumSize(QtCore.QSize(200, 0))
        self.labelDate.setMaximumSize(QtCore.QSize(200, 35))
        self.labelDate.setStyleSheet("background-color: rgba(255, 255, 255, 90);\n"
"                border: 1px solid rgba(255, 255, 255, 50);\n"
"                border-radius: 10px;\n"
"                font-size: 14px;")
        self.labelDate.setObjectName("labelDate")
        self.horizontalLayout.addWidget(self.labelDate)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 350))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 350))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"background-color: rgba(255, 255, 255, 90);\n"
"border: 1px solid rgba(255, 255, 255, 50);\n"
"border-radius: 10px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutAchievements = QtWidgets.QVBoxLayout()
        self.verticalLayoutAchievements.setObjectName("verticalLayoutAchievements")
        self.verticalLayout_5.addLayout(self.verticalLayoutAchievements)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(400, 100))
        self.groupBox_3.setStyleSheet("QGroupBox{\n"
"background-color: rgb(234, 144, 11);\n"
"color: rgb(255, 229, 153);\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px;\n"
"}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelGoals = QtWidgets.QLabel(parent=self.groupBox_3)
        self.labelGoals.setMinimumSize(QtCore.QSize(300, 0))
        self.labelGoals.setMaximumSize(QtCore.QSize(16777215, 45))
        self.labelGoals.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.labelGoals.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelGoals.setObjectName("labelGoals")
        self.verticalLayout_3.addWidget(self.labelGoals)
        self.progressBar = QtWidgets.QProgressBar(parent=self.groupBox_3)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(600, 500))
        self.groupBox.setMaximumSize(QtCore.QSize(600, 500))
        self.groupBox.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutPlots = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlots.setObjectName("verticalLayoutPlots")
        self.verticalLayout_2.addLayout(self.verticalLayoutPlots)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Thống kê mục tiêu"))
        self.pushButtonBack.setText(_translate("MainWindow", "Quay lại"))
        self.pushButtonBefore.setText(_translate("MainWindow", "<"))
        self.pushButtonAfter.setText(_translate("MainWindow", ">"))
        self.labelDate.setText(_translate("MainWindow", "Ngày:"))
        self.labelGoals.setText(_translate("MainWindow", "Đã đạt được mục tiêu tuần này"))
        self.groupBox.setTitle(_translate("MainWindow", "Năng suất cày cuốc tuần này"))
