# Form implementation generated from reading ui file 'D:\SmartStudy_het_loi_tkb\ui\timer.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(209, 569, 141, 71))
        self.btn_start.setStyleSheet("border-image: url(:/images/ui/images/start.png);")
        self.btn_start.setText("")
        self.btn_start.setObjectName("btn_start")
        self.btn_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(358, 569, 151, 71))
        self.btn_pause.setStyleSheet("border-image: url(:/images/images/pause.png);\n"
"border-image: url(:/images/ui/images/pause.png);")
        self.btn_pause.setText("")
        self.btn_pause.setObjectName("btn_pause")
        self.btn_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(528, 577, 151, 51))
        self.btn_stop.setStyleSheet("border-image: url(:/images/ui/images/finish.qrc.png);")
        self.btn_stop.setText("")
        self.btn_stop.setObjectName("btn_stop")
        self.lbl_session = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_session.setGeometry(QtCore.QRect(308, 140, 16, 21))
        self.lbl_session.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_session.setObjectName("lbl_session")
        self.btn_exit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(868, 9, 161, 141))
        self.btn_exit.setStyleSheet("border-image: url(:/images/images/exit.png);\n"
"border-image: url(:/images/ui/images/exit.png);")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.spinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(258, 319, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("QSpinBox {\n"
"    background-color: #ADD8E6; /* Màu nền xanh dương nhạt giống ảnh */\n"
"    color: #333333;           /* Màu số (đen/xám đậm cho rõ) */\n"
"    border: 2px solid black;   /* Thêm viền đen nếu muốn giống phong cách pixel */\n"
"\n"
"}\n"
"QSpinBox {\n"
"    padding-right: 15px; /* Đẩy số lùi sang trái chừa chỗ cho 2 nút */\n"
"}\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* Trói nút Lên vào góc trên bên phải */\n"
"    width: 20px;\n"
"}\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* Trói nút Xuống vào góc dưới bên phải */\n"
"    width: 20px;\n"
"}")
        self.spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(378, 319, 121, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("QSpinBox {\n"
"    background-color: #ADD8E6; /* Màu nền xanh dương nhạt giống ảnh */\n"
"    color: #333333;           /* Màu số (đen/xám đậm cho rõ) */\n"
"    border: 2px solid black;   /* Thêm viền đen nếu muốn giống phong cách pixel */\n"
"\n"
"\n"
"}\n"
"QSpinBox {\n"
"    padding-right: 15px; /* Đẩy số lùi sang trái chừa chỗ cho 2 nút */\n"
"}\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* Trói nút Lên vào góc trên bên phải */\n"
"    width: 20px;\n"
"}\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* Trói nút Xuống vào góc dưới bên phải */\n"
"    width: 20px;\n"
"}")
        self.spinBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(498, 319, 111, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("QSpinBox {\n"
"    background-color: #ADD8E6;\n"
"    color: #333333;\n"
"    border: 2px solid black;\n"
"}\n"
"QSpinBox {\n"
"    padding-right: 15px; /* Đẩy số lùi sang trái chừa chỗ cho 2 nút */\n"
"}\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right; /* Trói nút Lên vào góc trên bên phải */\n"
"    width: 20px;\n"
"}\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right; /* Trói nút Xuống vào góc dưới bên phải */\n"
"    width: 20px;\n"
"}")
        self.spinBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_3.setObjectName("spinBox_3")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(128, 189, 591, 401))
        self.frame.setStyleSheet("border-image: url(:/images/C:/Users/Admin/Downloads/bg.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.combo_subject = QtWidgets.QComboBox(parent=self.centralwidget)
        self.combo_subject.setGeometry(QtCore.QRect(480, 140, 141, 22))
        self.combo_subject.setObjectName("combo_subject")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(268, 109, 451, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.layoutWidget.raise_()
        self.frame.raise_()
        self.btn_stop.raise_()
        self.lbl_session.raise_()
        self.btn_start.raise_()
        self.btn_pause.raise_()
        self.btn_exit.raise_()
        self.spinBox.raise_()
        self.spinBox_2.raise_()
        self.spinBox_3.raise_()
        self.combo_subject.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Study - Đồng hồ đếm ngược"))
        self.lbl_session.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">1</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">PHIÊN HỌC</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">MÔN HỌC</span></p></body></html>"))
